# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SuperDaveLab.LedgerSprout
PackageVersion: 0.10.1
InstallerType: nullsoft
Scope: user
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
# electron-builder's NSIS GUID: UUIDv5 of the appId com.superdavelab.ledgersprout
ProductCode: e6c4026f-a538-50f7-9b8e-b87ab64f7655
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://ledgersprout.superdavelab.com/downloads/electron/LedgerSprout.Setup.0.10.1.exe
  InstallerSha256: 5AABB0CA58783BB1598708E215A04BAF998389E98594DC978F0831B8AB7EDB52
  AppsAndFeaturesEntries:
  - ProductCode: e6c4026f-a538-50f7-9b8e-b87ab64f7655
ManifestType: installer
ManifestVersion: 1.12.0
