# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SuperDaveLab.GridDock
PackageVersion: 0.11.0
InstallerType: nullsoft
Scope: user
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
# electron-builder's NSIS GUID: UUIDv5 of the appId com.superdavelab.griddock
ProductCode: 2b6c0dcd-678d-5e9d-bdfa-69055661685c
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://griddock.superdavelab.com/downloads/electron/GridDock.Setup.0.11.0.exe
  InstallerSha256: CDFC1CED556FDC753FFAE015C5628A92F7C941A474C8C3299D886198EEA408FD
  AppsAndFeaturesEntries:
  - ProductCode: 2b6c0dcd-678d-5e9d-bdfa-69055661685c
ManifestType: installer
ManifestVersion: 1.12.0
